### ISSUE TITLE
Doesn’t iteroperate well with Netrw

### ISSUE THREAD

**Issue by equant** [ap/vim-buftabline#31] opened 2017-06-05 16:23 UTC
This is probably user error, and not a bug, but when I have buffers open, :bprev and :bnext work as expected, but when I do :e<CR> to get a file list, the file list becomes a buffer that I can not :prev.  

i.e. I can cycle past it using next, but previous doesn't work.  Also, the "tab" at the top isn't highlighted when I'm viewing the ":e" buffer.

Any ideas on how I'm supposed to be handling this situation?  Thanks.

**Comment by ap** [comment] 2017-06-05 20:26
That’s due to how the Netrw plugin works (which is what Vim uses to handle directory listings), unfortunately. In short, it puts its directory listing in a nameless hidden buffer. This is what ultimately drove me to write the [readdir](https://github.com/ap/vim-readdir) plugin. Trying to do it differently from Netrw then taught me why Netrw is written as it is – both approaches have their problems. I’m not sure what to do here really. I can’t tell everyone to install Readdir just to fix this, nor should they have to, nor would I recommend it to everyone any more. And in the end the UX is suboptimal either way. Kinda crappy situation.

**Comment by equant** [comment] 2017-06-21 02:24
Ok, thanks for the information about the issue.  I can live with it, and I'll try readdir to see if that works for me.

**Comment by ap** [comment] 2018-01-28 14:13
(Duplicate of #25, reclosing)

**Closed by ap** 2018-01-28 14:13 UTC
Labels: duplicate
